services:
  # Service principal - API Backend
  - type: web
    name: deliveryp2p-api
    runtime: docker
    plan: starter
    buildCommand: composer install --optimize-autoloader --no-dev --no-interaction
    startCommand: php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /api/health
    envVars:
      # Configuration de l'application
      - key: APP_NAME
        value: "LivraisonP2P"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://deliveryp2p-api.onrender.com"
      
      # Configuration Supabase (à configurer manuellement)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # Configuration JWT et sécurité (à configurer manuellement)
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: QR_CODE_SECRET
        sync: false
      - key: PASSWORD_SALT
        sync: false
      
      # Configuration des logs
      - key: LOG_LEVEL
        value: "info"
      
      # Configuration du cache
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_TTL
        value: "3600"
      
      # Configuration du rate limiting
      - key: RATE_LIMIT_REQUESTS
        value: "100"
      - key: RATE_LIMIT_WINDOW
        value: "3600"
      
      # Configuration des fichiers
      - key: UPLOAD_MAX_SIZE
        value: "10485760"
      
      # Configuration des QR codes
      - key: QR_CODE_SIZE
        value: "300"
      - key: QR_CODE_MARGIN
        value: "10"
      - key: QR_CODE_ERROR_CORRECTION
        value: "M"
      
      # Configuration des livraisons
      - key: DELIVERY_RADIUS_KM
        value: "0.5"
      - key: DELIVERY_TIMEOUT_MINUTES
        value: "30"
      - key: MAX_DELIVERY_WEIGHT_KG
        value: "25"
      
      # Configuration des commissions
      - key: PLATFORM_COMMISSION_PERCENT
        value: "15"
      - key: MINIMUM_DELIVERY_FEE
        value: "5"
      
      # Configuration des notifications
      - key: PUSH_NOTIFICATIONS_ENABLED
        value: "true"
      - key: EMAIL_NOTIFICATIONS_ENABLED
        value: "true"
      - key: SMS_NOTIFICATIONS_ENABLED
        value: "false"
      
      # Configuration des timezones
      - key: TIMEZONE
        value: "Europe/Paris"
      - key: LOCALE
        value: "fr_FR.UTF-8"
      
      # Configuration de la mémoire
      - key: MEMORY_LIMIT
        value: "256M"
      - key: MAX_EXECUTION_TIME
        value: "30"
      
      # Configuration PHP
      - key: PHP_VERSION
        value: "8.2"
      - key: COMPOSER_MEMORY_LIMIT
        value: "-1"
    autoDeploy: true
    branch: main

# Base de données PostgreSQL (optionnel - peut utiliser Supabase)
databases:
  - name: deliveryp2p-db
    databaseName: deliveryp2p
    user: deliveryp2p_user
    plan: starter
    ipAllowList: [] 