services:
  # Service Frontend
  - type: web
    name: deliveryp2p-frontend
    env: static
    buildCommand: echo "Frontend static files"
    startCommand: echo "Frontend served by Render"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /auth/*
        destination: /auth/index.html
      - type: rewrite
        source: /*
        destination: /index.html

  # Service API
  - type: web
    name: deliveryp2p-api
    env: php
    buildCommand: echo "No build required for PHP"
    startCommand: cd api && php -S 0.0.0.0:$PORT index-simple.php
    envVars:
      - key: APP_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false 